version: '3.8'

services:
  wacrm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wacrm-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
